### ISSUE TITLE
Make Software Requirement Specification (SRS) file

### ISSUE THREAD

**Issue by Shubham-Zone** [Shubham-Zone/Citizen_Squad#11]
An SRS is a detailed document that defines the functional and non-functional requirements of a software system. It provides a comprehensive description of how the software should behave, its features, constraints, and the performance standards it must meet, serving as a blueprint for developers and ensuring alignment with user needs.

**Comment by iPriyanshu19** [comment]
Add hacktoberfest and gssoc-extended label to your repo.

**Comment by PhilipJohn005** [comment]
should it be in word file or pdf file?

**Comment by Shubham-Zone** [comment]
if possible give me both

**Comment by PhilipJohn005** [comment]
[srs_citizen_squad.pdf](https://github.com/user-attachments/files/17535014/srs_citizen_squad.pdf)
will this work??The comment section doesnt accept .word so i sent .pdf

**Comment by Shubham-Zone** [comment]
@PhilipJohn005 This is awesome!
