### ISSUE TITLE
 adding code_of conduct.md

### ISSUE THREAD

**Issue by jyothimanoj12** [Shubham-Zone/Citizen_Squad#19]
A Code of Conduct ensures inclusivity, prevents harassment, clarifies behavioral expectations, encourages professionalism, and fosters a safe, welcoming community for contributors.

plz assisn me this issue under gsoc-extended , level 1 , hacktoberfest-accepted tag

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
And please add gssoc-ext label

**Comment by jyothimanoj12** [comment]
Done

**Comment by jyothimanoj12** [comment]
Hey @Shubham-Zone its done
