### ISSUE TITLE
Dashboard for Municipal Authorities

### ISSUE THREAD

**Issue by Shubham-Zone** [Shubham-Zone/Citizen_Squad#36]
Create a dedicated dashboard for municipal authorities to manage and track reports from the Citizen Squad app. This will help authorities prioritize and resolve issues efficiently, improving the resolution process.

**Comment by lavitratyagi1** [comment]
Can you please tell from where and what type of data will be displayed in that dashboard and what features you need in your app?
As i want to contribute in your project i want few details that i need to work on this issue.

**Comment by Shubham-Zone** [comment]
Create a new dashboard page in the client app with data visualization features, which will later be merged into the admin app.

Features to Implement:

1. Graphs and Charts for Reports
   - Use charts (e.g., line, bar, pie) to show:
     - Number of reports over time.
     - Reports by issue type (potholes, vehicles, garbage).
   
2. Heatmap or Highlighted Map
   - Integrate a heatmap using Google Maps API to highlight areas with the most reports.
   - Allow filtering by issue type and time period.

3. Key Insights/Analytics
   - Display summary stats like total reports, resolved reports, average resolution time, and issue trends.
   - Use charts/graphs to display these insights (e.g., pie charts).

My admin app for this is not open source so just make this page in this client app with name somthing like .. admin_dashboard, i will merge this page with my admin app later on

**Comment by Shubham-Zone** [comment]
@lavitratyagi1 may you please star the repo

**Comment by lavitratyagi1** [comment]
Sir in your app as you have not provided mongo url so can you please tell me what should i do for testing purpose like should i use my own mongo url but then how i will know about database structure so can  you please provide me your mongo db url or its sturucture.

**Comment by Shubham-Zone** [comment]
@lavitratyagi1 dm me on linkedin will share the connection url with you but keep it private
