### ISSUE TITLE
AppBar Section Change Does Not Update Highlight on Selected Page

### ISSUE THREAD

**Issue by anurag-026** [Shubham-Zone/Citizen_Squad#4]
In the "Biotree" application, switching between sections in the AppBar (Home, Apply, Login, Dashboard) does not update the highlighted page indicator. Despite navigating to a new section, only the "Home" screen remains highlighted in the AppBar.

**Comment by Shubham-Zone** [comment]
@anurag-026 please show the issue with screen shots
