### ISSUE TITLE
Improve the UI  Apply page card .

### ISSUE THREAD

**Issue by Himanshu-kumar025** [Shubham-Zone/Citizen_Squad#42]
The cards of apply page is not good I would like to improve that card under GSSOC'24 and Hacktofest'24
thank you

![Screenshot 2024-10-22 183904](https://github.com/user-attachments/assets/a85daa46-1a3b-4638-a3f3-0b4e592bd192)

**Comment by Himanshu-kumar025** [comment]
@Shubham-Zone plz assign me on this issue under GSSOC'24 and Hacktofest'24 and levels 2/3 labels

**Comment by Shubham-Zone** [comment]
@Himanshu-kumar025 this interface is not in my app
