### ISSUE TITLE
Automate APK Build on Merge to Main Branch

### ISSUE THREAD

**Issue by sanjay14073** [Shubham-Zone/Citizen_Squad#5]
Description: Set up GitHub Actions to automatically build the Flutter APK when changes are merged into the main branch, and upload the APK as an artifact for easy download.

**Comment by sanjay14073** [comment]
@Shubham-Zone I would like to get this issue assigned to me under the GSSoC and Hacktoberfest labels. Could you please tag it accordingly?

**Comment by Shubham-Zone** [comment]
@sanjay14073 go ahead
