### ISSUE TITLE
Change Twitter Symbol to X in footer section

### ISSUE THREAD

**Issue by Amanjayswal500** [Shubham-Zone/Citizen_Squad#9]
I would like to propose a change to update the Twitter symbol to "X" to reflect Twitter's recent rebranding. This change ensures consistency with the platform's new identity and avoids any potential confusion for users.
please assign this issue to me
![Screenshot 2024-10-05 131051](https://github.com/user-attachments/assets/3db1df31-de8b-492c-ae40-a564f72a1096)

**Comment by Shubham-Zone** [comment]
@Amanjayswal500 there is no such symbols in my app can you please show me the ss ?

**Comment by Amanjayswal500** [comment]
@Shubham-Zone in footer section svg of the old Twitter logo.    I want to update to current logo to "X"
![Screenshot 2024-10-05 192800](https://github.com/user-attachments/assets/cc64376e-ee0a-447d-aae4-96d9f684e343)

**Comment by Shubham-Zone** [comment]
@Amanjayswal500 bro this screen is not present in my app .. ig there is a misunderstanding

**Comment by Avinash174** [comment]
I'd like to work on this issue
